remote: origin
target-branch: main
chart-dirs:
  - chart
helm-extra-args: --timeout 600s
check-version-increment: true
debug: true
validate-chart-schema: true
validate-maintainers: false
validate-yaml: true