apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pyroscope-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/MohithN02/pyroscope.git
    targetRevision: HEAD
    path: chart/pyroscope
  destination: 
    server: https://kubernetes.default.svc
    namespace: pyroscope-argocd

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
